spring:
  datasource:
    url: jdbc:mariadb://mysql-catachips.alwaysdata.net/catachips_catachips
    username: catachips_root
    password: 2idx6P5W
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop