spring:
  devtools:
    add-properties: false
  datasource:
    url: jdbc:mariadb://mysql-superchips.alwaysdata.net/superchips_catalogue
    username: 336651_lucas
    password: Lucas1234@
  jpa:
    database: mysql
    generate-ddl: true
    hibernate.ddl-auto: create-drop

server:
  port: 8022
